### ISSUE TITLE
Sorting for Offers

### ISSUE THREAD

**Issue by ismailoezcan** [fabfischer/kickbase-plus#27]
I think it would be nice to be able to sort the offers. Currently they are sorted from oldest offer to newest offer, but for me personally it would make sense to sort them the other way round and maybe even sorting for profit etc.

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,

thanks for your feedback. I will try to add sorting as soon as possible. I was actually planning to give the user more options to customize some details of the application to their own needs anyway. Sorting is a good start for this.

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,
I'm happy to report that you can now sort the offers. The setting can now also be changed under "Settings".
See #29

and check it out: https://kickbaseplus.fabian-fischer.com/#/settings
