### ISSUE TITLE
Re-Add all players to transfermarket

### ISSUE THREAD

**Issue by Quotic** [fabfischer/kickbase-plus#28]
Hey,

I think it would be useful to add a button to add all players again to transfermarket when the previous offer was to low! (custom value) i.E. re-add all where the offer is not more then 0,4% above market value.

**Comment by fabfischer** [comment]
Hi @Quotic ,

thanks for your feedback. I will most likely release/implement the feature with #27 (aka "give the user more personalization options") . I hope to have both finished by next week.

best,
Fabian

**Comment by Quotic** [comment]
sounds great, will looking forward to it!

**Comment by fabfischer** [comment]
Hi @Quotic ,
You can change the offers threshold now. The setting can now be changed under "Settings".
See #29

and check it out: https://kickbaseplus.fabian-fischer.com/#/settings

**Comment by Quotic** [comment]
Nice, so it is really time saving.
