### ISSUE TITLE
Bid input, thousands seperator

### ISSUE THREAD

**Issue by Quotic** [fabfischer/kickbase-plus#31]
Hi,

when possible add thousands seperator to bid input
![image](https://user-images.githubusercontent.com/1618550/185781199-210bf38b-ce10-4350-9a64-b883257e8a1c.png)

makes it easier to enter value manually.

**Comment by fabfischer** [comment]
Hi,
Thanks for your input. I will look into this as soon as I can. I'm currently on vacation, which is why it probably won't happen for 2 weeks.

Greetings, 
Fabian

**Comment by fabfischer** [comment]
Hi @Quotic,

I just want to let you know that I'm still working on the feature. I hope to be able to release it in the next week.

Fabian

**Comment by fabfischer** [comment]
Hi @Quotic ,

I just updated the preview version with a working thousand separators in the number field.

You can check it out here: https://kickbaseplus.fabian-fischer.com/#/transfermarket

It still has a small bug: if an offer is rejected by Kickbase's server, the value of the offer is set to 0 and you need to reload the TM. I will fix it asap.

**Comment by Quotic** [comment]
Hi @fabfischer,

Nice, exactly what I expected. But found another bug. When you erase the complete value to enter a new one it switch back to the original one. I hope you understand what I mean.

**Comment by fabfischer** [comment]
@all-contributors please add @Quotic for ideas
