### ISSUE TITLE
Option for not hiding player details when player has no offer

### ISSUE THREAD

**Issue by eLindros** [fabfischer/kickbase-plus#39]
I like to have the player details always visible. So an option to not hide them would be awesome.

<img width="1101" alt="Bildschirmfoto 2022-09-01 um 21 55 41" src="https://user-images.githubusercontent.com/4130049/188001645-c6f2bd7f-4008-46ee-aa95-79607de2b398.png">

**Comment by fabfischer** [comment]
Hi @eLindros ,

I added a new setting to change the behavior. You can set it in the settings view: 
![Screenshot 2022-10-17 at 19 02 39](https://user-images.githubusercontent.com/1053032/196239076-48d55c7b-f118-4885-af2c-1c137b585746.png)

You can try it with the current release candidate of version 1.6:
https://kickbaseplus.fabian-fischer.com/

Let me know what you think.

Fabian

**Comment by eLindros** [comment]
Thanks! Exactly was I was looking for.

**Comment by fabfischer** [comment]
@all-contributors please add @eLindros for ideas and code

**Comment by fabfischer** [comment]
Hi @eLindros  ,

I released it with version 1.6 (#58). 

please take a look or just test it here: https://kickbaseplus.fabian-fischer.com/

I will close this ticket, but if you have any further ideas, just contact me or open a new issue.

best,
Fabian
