### ISSUE TITLE
Option to re-add all players where the Kickbase offer has expired.

### ISSUE THREAD

**Issue by Quotic** [fabfischer/kickbase-plus#43]
I missed on a couple of players to add them again, Kickbase was expired but it wasn't really obvious. It may also be possible to highlight this visually.

**Comment by fabfischer** [comment]
Hi @Quotic ,

just to get it right: you would expect all expired offers to be rejected as well and the related players to be put back on the transfer market when you click "decline all offers that are too low"? Or do you see this as another button/option?

**Comment by Quotic** [comment]
So in my way to play it should be one button, because I sell only to kickbase and when this offer is expired it is useless to have this player on the transfermarket.

**Comment by fabfischer** [comment]
Hi @Quotic ,

if you now click the "decline all offers that are too low or expired"-button, all expired offers, which have only an offer from Kickbase, will be rejected and the player will be put back on the transfer market again. 

You can check out this feature here: https://kickbaseplus.fabian-fischer.com/#/sell

Please let me know if it works for you.

Greetings,
Fabian

**Comment by fabfischer** [comment]
I will close this issue, because the feature is fixed/added with 534356ed7a9cb69d8e1ebf242fa93970b49bba68, which will soon merged with the main branches. You can test it here: https://kickbaseplus.fabian-fischer.com/#/home
Or you can check out the feature branch "feature/1.6"
