### ISSUE TITLE
Change color for expired offers and soon to expire offers

### ISSUE THREAD

**Issue by ismailoezcan** [fabfischer/kickbase-plus#44]
Hi would be pretty nice if the color for expired offers would be different in any way. For example the color of the borders could be different. Maybe anybody else has a better idea 😃 

 ![image](https://user-images.githubusercontent.com/32710563/188733535-85bd08c7-b1ae-4de2-9090-3c00e5a8d2c3.jpeg)

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,

Good idea. I will change the color for expired offers in the next update.

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,

I added a new color (purple) to represent expired offers. In addition to this, it is no longer possible to accept an expired offer (the button is no longer displayed)

You can check a preview version here: https://kickbaseplus.fabian-fischer.com/
Please let me know what you think and if it works for you.

**Comment by fabfischer** [comment]
I will close this issue, because the feature is fixed/added with 534356ed7a9cb69d8e1ebf242fa93970b49bba68, which will soon merged with the main branches. You can test it here: https://kickbaseplus.fabian-fischer.com/#/home
Or you can check out the feature branch "feature/1.6"
