### ISSUE TITLE
Update market value change at 22:04

### ISSUE THREAD

**Issue by ismailoezcan** [fabfischer/kickbase-plus#45]
As you know Kickbase usually updates the market values as 22:04 o'clock. 
Would be pretty nice when you could see the change in market value immediately and don't have to wait until the next day for the next update in the api.

Could be calculated with help of the current market value which is immediately updated plus the latest market value change as long as they are not the same. In case they are the same then the process should be the same as it is now 
I hope I was able to explain it the right way.

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,

Thanks for the feedback. I will look into it, and probably change the behavior in the next update.

**Comment by fabfischer** [comment]
@all-contributors please add @ismailoezcan for feedback and idea

**Comment by fabfischer** [comment]
Hi @ismailoezcan ,

I changed the business logic for fetching market values. this should be sufficient to get always the latest market values.
I released it with version 1.6 (#58). 

please take a look or just test it here: https://kickbaseplus.fabian-fischer.com/

I will close this ticket, but if you have problems with this, just contact me or open a new issue.

Fabian
