### ISSUE TITLE
Bid -0.9% below market value too low?

### ISSUE THREAD

**Issue by eLindros** [fabfischer/kickbase-plus#46]
Sometimes when I bid 0.9% below the market value, kickbase declines my offer but without selling to someone else. Is this value of -0.9% maybe too low especially for players with higher market value? Then maybe it would be nice to add a safer option for bids below the market value. But I don't know which that could be.

**Comment by fabfischer** [comment]
Hi @eLindros ,

a bid with 0.9% lower than the market value is a bet. And nothing more. You can't be sure that Kickbase will accept it. 

The -0.9% results from my experience that this is the best compromise between "risky bet" and "get the player".
I don't know Kickbase's calculations, but: the higher you bid below market value, the less likely you will get the player.

So bidding just -0.4% market value is safer than -0.9%. But both bids might be rejected by Kickbase. 

**And another important note:** 
The more expensive a player is, the riskier it is to bid -0.9% below the market value. 

#### Examples:

##### 0.9% below market value
- I would argue, that -0.9% bid for a player with a market value of 500.000€ is a bet with a >99% chance of success
- Bidding -0.9% for a for a player with a market value of 5.000.000€ might be a bet with a 75% chance of success
- Bidding -0.9% for a player with a market value of higher than 10.000.000€ might be a bet with a 50% chance of success
- Bidding -0.9% for a player with a market value of higher than 20.000.000€ might be a bet with a 33% chance of success
- Bidding -0.9% for a player with a market value of higher than 30.000.000€ might be a bet with a 10-25% chance of success

##### 0.3% below market value
- Bidding -0.3% bid for a player with a market value of 500.000€ is a bet with a >99% chance of success
- Bidding -0.3% for a for a player with a market value of 5.000.000€ might be a bet with a >90% chance of success
- Bidding -0.3% for a player with a market value of higher than 10.000.000€ might be a bet with a >75% chance of success
- Bidding -0.3% for a player with a market value of higher than 20.000.000€ might be a bet with a >50% chance of success
- Bidding -0.3% for a player with a market value of higher than 30.000.000€ might be a bet with a >33% chance of success

(you get the idea)

You can bid 480.000 for a player with 500.000 market value, which is -4% below market value and Kickbase might be accept it. But it's very, very unlikely that Kickbase will accept a >-2% bid for a high-priced player.

If you want the player for sure, you have to bid the MV. Or for expensive players perhaps only bid 0.3% below the market value (which is still a bet on getting the player)

**Comment by eLindros** [comment]
Thanks! Didn't know that.

**Comment by fabfischer** [comment]
Hi @eLindros ,

I will close this ticket. I documented your question/my answer in a new wiki: https://github.com/fabfischer/kickbase-plus/wiki/FAQs
