### ISSUE TITLE
Displaying points scored by a player

### ISSUE THREAD

**Issue by FelixSchuSi** [fabfischer/kickbase-plus#56]
Hey @fabfischer,
thanks for building kickbase-plus.
I use the transfermarket page daily but I often find myself opening the phone app to see how a player has scored recently.
Displaying the points scored by a player would be a nice addition to kickbase-plus imo.
Im willing to open a PR and implement this feature myself.
I have built [something similair](https://felixschusi.github.io/better-kickbase-web/player/Jude%20Bellingham/2845/) before at [better-kickbase](https://github.com/FelixSchuSi/better-kickbase-web).

I plan to display the points scored in a new extension panel something like this:
![bellingham_mock](https://user-images.githubusercontent.com/47390169/195836337-c74e7585-5bd8-4059-9768-ac49e2913c68.png)

- Is there a chance that this feature would get merged?
- Do you have a better idea in mind how to display points scored?

**Comment by eLindros** [comment]
I really like the general idea and share the same experience with constant switching between Kickbase-plus and the Kickbase App. 

What is your approach with your project better-kickbase also compared to Kickbase-plus? Do you still develop this further?

**Comment by FelixSchuSi** [comment]
> What is your approach with your project better-kickbase also compared to Kickbase-plus? Do you still develop this further?
I dont plan to develop better-kickbase any further😅

**Comment by fabfischer** [comment]
Hi @FelixSchuSi ,

this is a great idea. I will look into it. Maybe I can "borrow" some of your code 1:1 - or at least benefit from your approach without much extra work

**Comment by fabfischer** [comment]
@all-contributors please add @FelixSchuSi for ideas
and @all-contributors please add @fabfischer for code

**Comment by fabfischer** [comment]
Hi @FelixSchuSi ,

I added this feature and released it with v1.6
![Screenshot 2022-10-28 at 16 14 25](https://user-images.githubusercontent.com/1053032/198638439-6016922b-779f-473f-a9d8-b219447240c5.png)


please check it out, or just test it here:  https://kickbaseplus.fabian-fischer.com/

I will close this ticket. But please contact me if you have any further ideas or issues with this feature.

Fabian
