### ISSUE TITLE
Display full time stamp on the transfer market

### ISSUE THREAD

**Issue by Quotic** [fabfischer/kickbase-plus#69]
![image](https://user-images.githubusercontent.com/1618550/198697261-70639982-8344-484e-a6df-17620fe192be.png)

I will not stop presenting my ideas :) 

There is sometimes the problem directly before matchdays that with the statement "In one hour" you are not sure whether the transfer is completed before the whistle or after the whistle. Therefore it would be advantageous if you could somehow get the full timestamp. This is part of the API. Maybe as a hover when you move the mouse over the time display?

**Comment by fabfischer** [comment]
Hi @Quotic ,

I added a feature to toggle the display of the expiration date. Both displays alternate every 7 seconds - but you can change this behaviour in the settings. And you can also change the initial display with another setting:

![Screenshot 2022-10-29 at 13 07 17](https://user-images.githubusercontent.com/1053032/198828002-2606a90d-7dc8-4e9f-912f-33ad57835227.png)

I released it with a new minor version.

Fabian
