### ISSUE TITLE
"did not play" hard to read

### ISSUE THREAD

**Issue by ismailoezcan** [fabfischer/kickbase-plus#77]
![image](https://user-images.githubusercontent.com/32710563/200899611-c7476ecb-d2d9-4289-b640-9a819a2a51f2.png)

I found it pretty hard to read when I first read the text on the screenshot.

Maybe a better way to show the information that a certain player did not play in a certain match would be to only show the "stop sign" and if possible to show the match (like for matches where the player played) 

Maybe something like this (only fast edit in DevTools)

![image](https://user-images.githubusercontent.com/32710563/200900584-2e61b6b1-5cce-4ff2-a3e1-fc979ba2669b.png)

**Comment by fabfischer** [comment]
Hi @ismailoezcan .

I added this feature. However, due to the API limitations, the feature is only available for the current season. (see #85)

best,
Fabian
